import type { AchievementDefinition } from "./achievementTypes";

export const ACHIEVEMENTS: AchievementDefinition[] = [
  {
    id: "meta_early_adopter",
    title: "Early Adopter",
    description: "Joined Life OS in its early days.",
    emoji: "🚀",
    category: "meta",
    rarity: "legendary",
    check: ({ accountAgeDays }) => accountAgeDays >= 0,
  },
  {
    id: "meta_all_modules",
    title: "Life Maximalist",
    description: "Enabled all 10 core modules.",
    emoji: "🌟",
    category: "meta",
    rarity: "epic",
    check: ({ enabledModules }) => {
      const core = ["goals", "fitness", "nutrition", "reading", "todos", "schedule"];
      return core.every((m) => enabledModules.includes(m));
    },
  },

  {
    id: "goals_first",
    title: "Dream Catcher",
    description: "Created your first goal.",
    emoji: "🎯",
    category: "goals",
    rarity: "common",
    check: ({ goals }) => goals.length >= 1,
  },
  {
    id: "goals_five",
    title: "Big Thinker",
    description: "Created 5 goals.",
    emoji: "🧠",
    category: "goals",
    rarity: "rare",
    check: ({ goals }) => goals.length >= 5,
  },
  {
    id: "goals_first_step",
    title: "First Step",
    description: "Completed your first goal step.",
    emoji: "👣",
    category: "goals",
    rarity: "common",
    check: ({ goalStepCompletionsTotal }) => goalStepCompletionsTotal >= 1,
  },
  {
    id: "goals_first_completed",
    title: "Follow Through",
    description: "Completed your first goal.",
    emoji: "🏁",
    category: "goals",
    rarity: "rare",
    check: ({ goalsCompletedTotal }) => goalsCompletedTotal >= 1,
  },
  {
    id: "goals_three_completed",
    title: "Momentum Builder",
    description: "Completed 3 goals.",
    emoji: "🚀",
    category: "goals",
    rarity: "epic",
    check: ({ goalsCompletedTotal }) => goalsCompletedTotal >= 3,
  },
  {
    id: "goals_ten_completed",
    title: "Unstoppable",
    description: "Completed 10 goals.",
    emoji: "👑",
    category: "goals",
    rarity: "legendary",
    check: ({ goalsCompletedTotal }) => goalsCompletedTotal >= 10,
  },
  {
    id: "goals_high_priority",
    title: "Laser Focused",
    description: "Set a goal to high priority.",
    emoji: "🎖️",
    category: "goals",
    rarity: "common",
    check: ({ goals }) => goals.some((g) => g.priority === "high"),
  },
  {
    id: "goals_planner",
    title: "Master Planner",
    description: "Created a goal with 8 or more steps.",
    emoji: "📋",
    category: "goals",
    rarity: "rare",
    check: ({ goals }) => goals.some((g) => g.steps.length >= 8),
  },
  {
    id: "goals_steps_ten",
    title: "Action Taker",
    description: "Completed 10 goal steps.",
    emoji: "⚡",
    category: "goals",
    rarity: "rare",
    check: ({ goalStepCompletionsTotal }) => goalStepCompletionsTotal >= 10,
  },
  {
    id: "goals_steps_twenty",
    title: "Momentum Machine",
    description: "Completed 20 goal steps.",
    emoji: "🔥",
    category: "goals",
    rarity: "epic",
    check: ({ goalStepCompletionsTotal }) => goalStepCompletionsTotal >= 20,
  },
  {
    id: "goals_steps_hundred",
    title: "Century of Progress",
    description: "Completed 100 goal steps.",
    emoji: "💯",
    category: "goals",
    rarity: "legendary",
    check: ({ goalStepCompletionsTotal }) => goalStepCompletionsTotal >= 100,
  },

  {
    id: "fitness_first_pr",
    title: "Iron Starter",
    description: "Logged your first PR.",
    emoji: "🏋️",
    category: "fitness",
    rarity: "common",
    check: ({ fitness }) => {
      if (!fitness) return false;
      return Object.values(fitness.lifts).some((lift) => lift.history.length > 0);
    },
  },
  {
    id: "fitness_all_lifts",
    title: "Full Rack",
    description: "Logged a PR for every barbell lift.",
    emoji: "🏆",
    category: "fitness",
    rarity: "rare",
    check: ({ fitness }) => {
      if (!fitness) return false;
      const barbellLifts = Object.values(fitness.lifts).filter(
        (lift) => lift.category === "barbell",
      );
      return barbellLifts.length > 0 && barbellLifts.every((lift) => lift.history.length > 0);
    },
  },
  {
    id: "fitness_beat_goal",
    title: "Goal Crusher",
    description: "Beat your target on any lift.",
    emoji: "💥",
    category: "fitness",
    rarity: "epic",
    check: ({ fitness }) => {
      if (!fitness) return false;
      return Object.values(fitness.lifts).some((lift) => {
        if (!lift.history.length) return false;
        const best = Math.max(...lift.history.map((entry) => entry.value));
        return best >= lift.goal;
      });
    },
  },
  {
    id: "fitness_crossfit",
    title: "CrossFitter",
    description: "Logged a CrossFit skill PR.",
    emoji: "⚡",
    category: "fitness",
    rarity: "common",
    check: ({ fitness }) => {
      if (!fitness) return false;
      return Object.values(fitness.lifts)
        .filter((lift) => lift.category === "crossfit")
        .some((lift) => lift.history.length > 0);
    },
  },
  {
    id: "fitness_swimmer",
    title: "Aquanaut",
    description: "Logged a swimming PR.",
    emoji: "🏊",
    category: "fitness",
    rarity: "common",
    check: ({ fitness }) => {
      if (!fitness) return false;
      return Object.values(fitness.lifts)
        .filter((lift) => lift.category === "swimming")
        .some((lift) => lift.history.length > 0);
    },
  },
  {
    id: "fitness_ten_prs",
    title: "PR Machine",
    description: "Logged 10 total PRs across all lifts.",
    emoji: "📈",
    category: "fitness",
    rarity: "epic",
    check: ({ fitness }) => {
      if (!fitness) return false;
      const total = Object.values(fitness.lifts).reduce(
        (sum, lift) => sum + lift.history.length,
        0,
      );
      return total >= 10;
    },
  },
  {
    id: "fitness_first_workout_day",
    title: "Checked In",
    description: "Completed your first workout day.",
    emoji: "✅",
    category: "fitness",
    rarity: "common",
    check: ({ fitnessCompletedWorkoutDays, fitnessWorkoutStreak }) =>
      fitnessCompletedWorkoutDays >= 1 || fitnessWorkoutStreak >= 1,
  },
  {
    id: "fitness_streak_week",
    title: "Weekly Fire",
    description: "Built a 1 week workout streak.",
    emoji: "🔥",
    category: "fitness",
    rarity: "rare",
    check: ({ fitnessWorkoutStreak }) => fitnessWorkoutStreak >= 7,
  },
  {
    id: "fitness_streak_month",
    title: "Unbroken",
    description: "Built a 1 month workout streak.",
    emoji: "🗓️",
    category: "fitness",
    rarity: "legendary",
    check: ({ fitnessWorkoutStreak }) => fitnessWorkoutStreak >= 30,
  },

  {
    id: "nutrition_first_log",
    title: "Bon Appétit",
    description: "Logged your first meal.",
    emoji: "🍽️",
    category: "nutrition",
    rarity: "common",
    check: ({ nutritionLog }) => {
      if (!nutritionLog) return false;
      return (
        Object.values(nutritionLog.eaten ?? {}).some(Boolean) ||
        (nutritionLog.customEntries ?? []).length > 0
      );
    },
  },
  {
    id: "nutrition_full_day",
    title: "Clean Plate",
    description: "Logged breakfast, lunch, and dinner in a single day.",
    emoji: "🥇",
    category: "nutrition",
    rarity: "rare",
    check: ({ nutritionLog }) => {
      if (!nutritionLog) return false;
      const eaten = nutritionLog.eaten ?? {};
      const hasBreakfast = !!(eaten.breakfast1 || eaten.breakfast2);
      const hasLunch = !!(eaten.lunchWfh || eaten.lunchOffice);
      const hasDinner = !!eaten.dinner;
      return hasBreakfast && hasLunch && hasDinner;
    },
  },
  {
    id: "nutrition_logged_7_days",
    title: "Consistent Fueler",
    description: "Logged meals on 7 different days.",
    emoji: "⛽️",
    category: "nutrition",
    rarity: "rare",
    check: ({ nutritionLoggedDaysTotal }) => nutritionLoggedDaysTotal >= 7,
  },
  {
    id: "nutrition_logged_30_days",
    title: "Nutrition Nerd",
    description: "Logged meals on 30 different days.",
    emoji: "📊",
    category: "nutrition",
    rarity: "epic",
    check: ({ nutritionLoggedDaysTotal }) => nutritionLoggedDaysTotal >= 30,
  },
  {
    id: "nutrition_custom",
    title: "Off Menu",
    description: "Added your first custom meal entry.",
    emoji: "🍳",
    category: "nutrition",
    rarity: "common",
    check: ({ nutritionLog }) => (nutritionLog?.customEntries ?? []).length > 0,
  },
  {
    id: "nutrition_five_custom",
    title: "Chef's Special",
    description: "Added 5 custom meal entries.",
    emoji: "👨‍🍳",
    category: "nutrition",
    rarity: "rare",
    check: ({ nutritionLog }) => (nutritionLog?.customEntries ?? []).length >= 5,
  },
  {
    id: "nutrition_protein_target",
    title: "Protein Priority",
    description: "Hit your protein target for the first time.",
    emoji: "🥩",
    category: "nutrition",
    rarity: "common",
    check: ({ nutritionProteinTargetHitDays }) => nutritionProteinTargetHitDays >= 1,
  },
  {
    id: "nutrition_on_target",
    title: "Dialed In",
    description: "Finished a day within your macro target range.",
    emoji: "🎯",
    category: "nutrition",
    rarity: "rare",
    check: ({ nutritionOnTargetDays }) => nutritionOnTargetDays >= 1,
  },
  {
    id: "nutrition_three_on_target",
    title: "Macro Rhythm",
    description: "Hit your macro target on 3 different days.",
    emoji: "📈",
    category: "nutrition",
    rarity: "rare",
    check: ({ nutritionOnTargetDays }) => nutritionOnTargetDays >= 3,
  },
  {
    id: "nutrition_seven_on_target",
    title: "Macro Mastery",
    description: "Hit your macro target on 7 different days.",
    emoji: "🏅",
    category: "nutrition",
    rarity: "epic",
    check: ({ nutritionOnTargetDays }) => nutritionOnTargetDays >= 7,
  },
  {
    id: "nutrition_meal_prep",
    title: "Meal Prep Mindset",
    description: "Logged the same custom meal 5 times.",
    emoji: "🥣",
    category: "nutrition",
    rarity: "rare",
    check: ({ nutritionRepeatedCustomMealCount }) =>
      nutritionRepeatedCustomMealCount >= 5,
  },
  {
    id: "nutrition_week_streak",
    title: "Nutrition Week",
    description: "Logged meals every day for a full week.",
    emoji: "🗓️",
    category: "nutrition",
    rarity: "epic",
    check: ({ nutritionLongestLoggedStreak }) => nutritionLongestLoggedStreak >= 7,
  },
  {
    id: "nutrition_balanced_day",
    title: "Balanced Day",
    description: "Logged breakfast, lunch, dinner, and stayed on target.",
    emoji: "⚖️",
    category: "nutrition",
    rarity: "rare",
    check: ({ nutritionBalancedOnTargetDays }) => nutritionBalancedOnTargetDays >= 1,
  },

  {
    id: "reading_first_book",
    title: "Bookworm",
    description: "Added your first book.",
    emoji: "📖",
    category: "reading",
    rarity: "common",
    check: ({ reading }) => {
      if (!reading) return false;
      return reading.current.title.trim().length > 0;
    },
  },
  {
    id: "reading_finished_book",
    title: "Page Turner",
    description: "Finished a book.",
    emoji: "🎉",
    category: "reading",
    rarity: "rare",
    check: ({ readingBooksCompleted }) => readingBooksCompleted >= 1,
  },
  {
    id: "reading_three_books",
    title: "Shelf Builder",
    description: "Finished 3 books.",
    emoji: "📚",
    category: "reading",
    rarity: "epic",
    check: ({ readingBooksCompleted }) => readingBooksCompleted >= 3,
  },
  {
    id: "reading_ten_books",
    title: "Bibliophile",
    description: "Finished 10 books.",
    emoji: "🏛️",
    category: "reading",
    rarity: "legendary",
    check: ({ readingBooksCompleted }) => readingBooksCompleted >= 10,
  },
  {
    id: "reading_streak_7",
    title: "Daily Reader",
    description: "Maintained a 7-day reading streak.",
    emoji: "🔥",
    category: "reading",
    rarity: "rare",
    check: ({ readingStreak }) => readingStreak >= 7,
  },
  {
    id: "reading_streak_30",
    title: "Reading Machine",
    description: "Maintained a 30-day reading streak.",
    emoji: "💎",
    category: "reading",
    rarity: "legendary",
    check: ({ readingStreak }) => readingStreak >= 30,
  },
  {
    id: "reading_library",
    title: "To-Read Librarian",
    description: "Added 5 books to your up-next list.",
    emoji: "📚",
    category: "reading",
    rarity: "common",
    check: ({ reading }) => (reading?.upNext ?? []).length >= 5,
  },
  {
    id: "reading_goal_hit_first",
    title: "Locked In",
    description: "Reached your daily reading goal for the first time.",
    emoji: "🎯",
    category: "reading",
    rarity: "common",
    check: ({ readingGoalHitDays }) => readingGoalHitDays >= 1,
  },
  {
    id: "reading_goal_hit_seven",
    title: "Steady Reader",
    description: "Hit your daily reading goal on 7 different days.",
    emoji: "📅",
    category: "reading",
    rarity: "rare",
    check: ({ readingGoalHitDays }) => readingGoalHitDays >= 7,
  },
  {
    id: "reading_pages_100",
    title: "Page Pilot",
    description: "Read 100 pages total.",
    emoji: "💯",
    category: "reading",
    rarity: "rare",
    check: ({ readingPagesTotal }) => readingPagesTotal >= 100,
  },
  {
    id: "reading_pages_500",
    title: "Deep Reader",
    description: "Read 500 pages total.",
    emoji: "📘",
    category: "reading",
    rarity: "epic",
    check: ({ readingPagesTotal }) => readingPagesTotal >= 500,
  },

  {
    id: "todos_first",
    title: "Task Master",
    description: "Completed your first task.",
    emoji: "✅",
    category: "todos",
    rarity: "common",
    check: ({ todoCompletionEventsTotal }) => todoCompletionEventsTotal >= 1,
  },
  {
    id: "todos_ten",
    title: "Getting Things Done",
    description: "Completed 10 tasks total.",
    emoji: "📝",
    category: "todos",
    rarity: "rare",
    check: ({ todoCompletionEventsTotal }) => todoCompletionEventsTotal >= 10,
  },
  {
    id: "todos_twenty_five",
    title: "Momentum Maker",
    description: "Completed 25 tasks total.",
    emoji: "🚀",
    category: "todos",
    rarity: "epic",
    check: ({ todoCompletionEventsTotal }) => todoCompletionEventsTotal >= 25,
  },
  {
    id: "todos_three_in_day",
    title: "Productive Burst",
    description: "Completed 3 tasks in a single day.",
    emoji: "⚡",
    category: "todos",
    rarity: "rare",
    check: ({ todoBestDayCompletions }) => todoBestDayCompletions >= 3,
  },
  {
    id: "todos_streak_week",
    title: "Steady Hands",
    description: "Completed at least 1 task for 7 straight days.",
    emoji: "🔥",
    category: "todos",
    rarity: "epic",
    check: ({ todoCompletionStreak }) => todoCompletionStreak >= 7,
  },
  {
    id: "todos_inbox_zero",
    title: "Inbox Zero",
    description: "Finished all open tasks while having at least 5 tasks on your list.",
    emoji: "📬",
    category: "todos",
    rarity: "rare",
    check: ({ todos }) => todos.length >= 5 && todos.every((t) => t.done),
  },
  {
    id: "todos_clear_list",
    title: "Clean Slate",
    description: "Cleared your entire to-do list.",
    emoji: "🧹",
    category: "todos",
    rarity: "rare",
    check: ({ todos }) => todos.length > 0 && todos.every((t) => t.done),
  },

  {
    id: "water_first_goal_hit",
    title: "Hydrated",
    description: "Hit your hydration goal for the first time.",
    emoji: "💧",
    category: "water",
    rarity: "common",
    check: ({ waterGoalHitDays }) => waterGoalHitDays >= 1,
  },
  {
    id: "water_three_goal_days",
    title: "Flow State",
    description: "Hit your hydration goal on 3 different days.",
    emoji: "🌊",
    category: "water",
    rarity: "rare",
    check: ({ waterGoalHitDays }) => waterGoalHitDays >= 3,
  },
  {
    id: "water_seven_goal_days",
    title: "Always Filled",
    description: "Hit your hydration goal on 7 different days.",
    emoji: "🫗",
    category: "water",
    rarity: "epic",
    check: ({ waterGoalHitDays }) => waterGoalHitDays >= 7,
  },
  {
    id: "water_ten_liters",
    title: "Deep Drink",
    description: "Logged 10 liters of water total.",
    emoji: "🚰",
    category: "water",
    rarity: "rare",
    check: ({ waterLoggedTotalMl }) => waterLoggedTotalMl >= 10_000,
  },
  {
    id: "water_fifty_liters",
    title: "Hydration Hero",
    description: "Logged 50 liters of water total.",
    emoji: "🏞️",
    category: "water",
    rarity: "legendary",
    check: ({ waterLoggedTotalMl }) => waterLoggedTotalMl >= 50_000,
  },

  {
    id: "sleep_first_log",
    title: "Lights Out",
    description: "Logged your first night of sleep.",
    emoji: "🌙",
    category: "sleep",
    rarity: "common",
    check: ({ sleepLoggedDaysTotal }) => sleepLoggedDaysTotal >= 1,
  },
  {
    id: "sleep_seven_logs",
    title: "Rest Tracker",
    description: "Logged 7 nights of sleep.",
    emoji: "😴",
    category: "sleep",
    rarity: "rare",
    check: ({ sleepLoggedDaysTotal }) => sleepLoggedDaysTotal >= 7,
  },
  {
    id: "sleep_thirty_logs",
    title: "Sleep Student",
    description: "Logged 30 nights of sleep.",
    emoji: "🛌",
    category: "sleep",
    rarity: "epic",
    check: ({ sleepLoggedDaysTotal }) => sleepLoggedDaysTotal >= 30,
  },
  {
    id: "sleep_seven_hours_once",
    title: "Fully Recharged",
    description: "Logged 7+ hours of sleep once.",
    emoji: "🔋",
    category: "sleep",
    rarity: "common",
    check: ({ sleepSevenHourNights }) => sleepSevenHourNights >= 1,
  },
  {
    id: "sleep_seven_hours_seven_nights",
    title: "Rest Rhythm",
    description: "Logged 7+ hours of sleep on 7 nights.",
    emoji: "🗓️",
    category: "sleep",
    rarity: "epic",
    check: ({ sleepSevenHourNights }) => sleepSevenHourNights >= 7,
  },
  {
    id: "sleep_high_quality",
    title: "Quality Sleep",
    description: "Logged a sleep quality score of 80+.",
    emoji: "✨",
    category: "sleep",
    rarity: "rare",
    check: ({ sleepHighQualityNights }) => sleepHighQualityNights >= 1,
  },

  {
    id: "wellbeing_first_checkin",
    title: "Checked In",
    description: "Saved your first wellbeing check-in.",
    emoji: "💚",
    category: "wellbeing",
    rarity: "common",
    check: ({ wellbeingCheckInsTotal }) => wellbeingCheckInsTotal >= 1,
  },
  {
    id: "wellbeing_seven_checkins",
    title: "Inner Rhythm",
    description: "Saved 7 wellbeing check-ins.",
    emoji: "🌿",
    category: "wellbeing",
    rarity: "rare",
    check: ({ wellbeingCheckInsTotal }) => wellbeingCheckInsTotal >= 7,
  },
  {
    id: "wellbeing_first_journal",
    title: "Open Page",
    description: "Wrote your first journal entry.",
    emoji: "📝",
    category: "wellbeing",
    rarity: "common",
    check: ({ wellbeingJournalDays }) => wellbeingJournalDays >= 1,
  },
  {
    id: "wellbeing_seven_journal_days",
    title: "Reflective",
    description: "Journaled on 7 different days.",
    emoji: "📔",
    category: "wellbeing",
    rarity: "rare",
    check: ({ wellbeingJournalDays }) => wellbeingJournalDays >= 7,
  },
  {
    id: "wellbeing_first_gratitude",
    title: "Grateful",
    description: "Added your first gratitude note.",
    emoji: "🙏",
    category: "wellbeing",
    rarity: "common",
    check: ({ wellbeingGratitudeDays }) => wellbeingGratitudeDays >= 1,
  },
  {
    id: "wellbeing_seven_gratitude_days",
    title: "Grounded",
    description: "Added gratitude notes on 7 different days.",
    emoji: "🌤️",
    category: "wellbeing",
    rarity: "rare",
    check: ({ wellbeingGratitudeDays }) => wellbeingGratitudeDays >= 7,
  },

  {
    id: "skincare_first_am",
    title: "Morning Glow",
    description: "Completed your first AM skincare routine.",
    emoji: "🌞",
    category: "skincare",
    rarity: "common",
    check: ({ skincareAmCompletedEver }) => skincareAmCompletedEver,
  },
  {
    id: "skincare_first_pm",
    title: "Night Reset",
    description: "Completed your first PM skincare routine.",
    emoji: "🌙",
    category: "skincare",
    rarity: "common",
    check: ({ skincarePmCompletedEver }) => skincarePmCompletedEver,
  },
  {
    id: "skincare_first_full_day",
    title: "Full Routine",
    description: "Completed both AM and PM skincare in one day.",
    emoji: "✨",
    category: "skincare",
    rarity: "rare",
    check: ({ skincareFullDaysCompletedEver }) => skincareFullDaysCompletedEver,
  },
  {
    id: "skincare_streak_week",
    title: "Glow Streak",
    description: "Built a 7-day skincare streak.",
    emoji: "🔥",
    category: "skincare",
    rarity: "epic",
    check: ({ skincareStreak }) => skincareStreak >= 7,
  },
  {
    id: "skincare_first_log",
    title: "Skin Notes",
    description: "Saved your first skin log.",
    emoji: "🫧",
    category: "skincare",
    rarity: "common",
    check: ({ skincareSkinLogsTotal }) => skincareSkinLogsTotal >= 1,
  },
  {
    id: "skincare_seven_logs",
    title: "Skin Student",
    description: "Saved 7 skin logs.",
    emoji: "🪞",
    category: "skincare",
    rarity: "rare",
    check: ({ skincareSkinLogsTotal }) => skincareSkinLogsTotal >= 7,
  },

  {
    id: "finance_first_budget",
    title: "Budget Builder",
    description: "Set your first category budget.",
    emoji: "💸",
    category: "finance",
    rarity: "common",
    check: ({ financeHasBudgetSet }) => financeHasBudgetSet,
  },
  {
    id: "finance_first_expense",
    title: "Money Mapped",
    description: "Logged your first expense.",
    emoji: "🧾",
    category: "finance",
    rarity: "common",
    check: ({ financeHasExpenseLogged }) => financeHasExpenseLogged,
  },
  {
    id: "finance_monthly_plan",
    title: "Monthly Plan Built",
    description: "Set income and budgets for at least 3 categories.",
    emoji: "📊",
    category: "finance",
    rarity: "rare",
    check: ({ financeMonthlyPlansBuilt }) => financeMonthlyPlansBuilt >= 1,
  },
  {
    id: "finance_under_budget_three",
    title: "Under Control",
    description: "Stayed under budget in 3 categories.",
    emoji: "🎯",
    category: "finance",
    rarity: "rare",
    check: ({ financeUnderBudgetCategoryWins }) => financeUnderBudgetCategoryWins >= 3,
  },
  {
    id: "finance_savings_started",
    title: "Saver",
    description: "Added money to savings for the first time.",
    emoji: "🏦",
    category: "finance",
    rarity: "common",
    check: ({ financeSavingsTotal }) => financeSavingsTotal > 0,
  },
  {
    id: "finance_saved_1000",
    title: "Four Figures",
    description: "Saved 1,000 total.",
    emoji: "💰",
    category: "finance",
    rarity: "rare",
    check: ({ financeSavingsTotal }) => financeSavingsTotal >= 1_000,
  },
  {
    id: "finance_saved_5000",
    title: "Money Momentum",
    description: "Saved 5,000 total.",
    emoji: "📈",
    category: "finance",
    rarity: "epic",
    check: ({ financeSavingsTotal }) => financeSavingsTotal >= 5_000,
  },
  {
    id: "finance_saved_10000",
    title: "Cash Cushion",
    description: "Saved 10,000 total.",
    emoji: "👑",
    category: "finance",
    rarity: "legendary",
    check: ({ financeSavingsTotal }) => financeSavingsTotal >= 10_000,
  },

  {
    id: "streaks_reading_3",
    title: "Habit Forming",
    description: "3-day reading streak.",
    emoji: "🌱",
    category: "streaks",
    rarity: "common",
    check: ({ readingStreak }) => readingStreak >= 3,
  },
  {
    id: "streaks_reading_14",
    title: "Two Weeks Strong",
    description: "14-day reading streak.",
    emoji: "💪",
    category: "streaks",
    rarity: "epic",
    check: ({ readingStreak }) => readingStreak >= 14,
  },
];
